GenomeTag/urls.py
from django.urls import path
from . import views
from .views import SignUpView
from . import views

app_name = "GenomeTag"

urlpatterns = [
    path("", views.main, name="main"),
    path("", views.main, name="base"),
    path("userPermission/", views.userPermission, name="userPermission"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("informations/", views.log_info, name="log_info"),
    path("addfile/", views.addfile, name="addfile"),
    path("annotations/", views.annotations, name="annotations"),
    path("attributions/", views.attributions, name="attributions"),
    path("reviews_list/", views.reviews_list, name="reviews_list"),
    path("forum/", views.forum_main, name="forum_main"),
    path("forum/<int:topic_id>/", views.topic, name="topic"),
    path("like/<int:message_id>/", views.like_message, name="like_message"),
    path("create/", views.create, name="create"),
    path("search/", views.search, name="search"),
    path("review/<str:id>/", views.review_add, name="display_review"),
    path("result/", views.result, name="result"),
    path("create/create_peptide", views.create_peptide, name="create_peptide"),
    path(
        "create/create_annotation/<int:attribution_id>/",
        views.create_annotation,
        name="create_annotation",
    ),
    path(
        "create/modify_annotation/<str:annotation_id>/",
        views.modify_annotation,
        name="modify_annotation",
    ),
    path("delete_annotation/<int:attribution_id>/", views.delete_annotation, name="delete_annotation"),
    path("result/Genome/<str:id>/", views.genome, name="display_genome"),
    path("result/Genome/<str:genome_id>/<str:id>/", views.chromosome, name="display_chromosome"),
    path("result/Peptide/<str:id>/", views.peptide, name="display_peptide"),
    path("result/Annotation/<str:id>/", views.annotation, name="display_annotation"),
    path("result/Tag/<str:id>/", views.tag, name="display_tag"),
    path("download_fasta/<str:genome_id>/", views.download_fasta, name="download_fasta"),
    path(
        "download_fasta/<str:genome_id>/<str:chromosome_id>/",
        views.download_fasta_single_chromosome,
        name="download_fasta_single_chromosome",
    ),
    path(
        "download_peptide_fasta/<int:peptide_id>/",
        views.download_peptide_fasta,
        name="download_peptide_fasta",
    ),
    path(
        "download_annotation_fasta/<str:annotation_id>/",
        views.download_annotation_fasta,
        name="download_annotation_fasta",
    ),
    path(
        "download_all_annotation_fasta/<str:genome_id>/<str:chromosome_id>/",
        views.download_all_annotation_fasta,
        name="download_all_annotation_fasta",
    ),
    path("create/create_attribution/", views.create_attribution, name="create_attribution"),
    path("blast/", views.blast, name="blast"),
    path("blast_result/", views.blast_result, name="blast_result"),
    path("alternative_database/", views.alternative_database, name="alternative_database"),
    path("role_change/", views.role_change_request, name="role_change"),
    path("mailbox/", views.mailbox, name="mailbox"),
    path("compose/", views.compose_email, name="compose_email"),
    path("mailbox/<int:message_id>/", views.message_detail, name="message_detail"),
    path("mailbox/<int:message_id>/delete/", views.delete_message, name="delete_message"),
]

projet_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from django.urls import include
from django.views.generic import RedirectView


urlpatterns = [
    path("", RedirectView.as_view(url="/GenomeTag", permanent=False)),
    path("admin/", admin.site.urls),
    path("GenomeTag/", include("GenomeTag.urls")),
    path("GenomeTag/", include("django.contrib.auth.urls")),
]

GenomeTag/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy, reverse
from GenomeTag.models import (
    Genome,
    Chromosome,
    Position,
    Annotation,
    Peptide,
    Attribution,
    CustomUser,
    Tag,
    Review,
    CustomUser,
    Mailbox,
    Topic,
    Message,
)
from django.views.generic.edit import CreateView
from .forms import (
    CustomUserCreationForm,
    AnnotationForm,
    SearchForm,
    ReviewForm,
    PeptideForm,
    ChromosomeDescrForm,
    AttributionForm,
    FileAttributionForm,
    AnnotationDescrForm,
    createPeptideForm,
    ChangeForm,
    RoleChangeRequestForm,
    ComposeForm,
    PositionSelectionForm,
    BacteriaForm,
    TopicForm,
    MessageForm,
    addfileForm,
)
from GenomeTag.search_field import search_dic
import GenomeTag.build_query as bq
from .build_attribution import create_manual_attr, create_file_attr
from django.db.models import Q
import json
from django.views.generic.edit import CreateView
from GenomeTag.search_field import search_dic
import GenomeTag.build_query as bq
import xml.etree.ElementTree as ET
from .blast_utils import perform_blast
from prody import *

# Create your views here.


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"


def log_info(request):
    if request.user.is_authenticated:
        message = ""
        context = {}
        if request.method == "POST" and "sub1" in request.POST:
            form = ChangeForm(request.POST)
            if form.is_valid():
                if "username" in form.changed_data:
                    if (form.cleaned_data["username"] != "" or len(form.cleaned_data["username"]) <= 150) and all(
                        [(i in ["@", "_", "+", "."] or i.isalnum()) for i in form.cleaned_data["username"]]
                    ):
                        request.user.username = form.cleaned_data["username"]
                    else:
                        message += "Invalide username:\n Required. 150 characters or fewer. Usernames may contain alphanumeric, _, @, +, . and - characters. \n"
                if "phone" in form.changed_data:
                    if form.cleaned_data["phone"].is_valid():
                        request.user.phone = form.cleaned_data["phone"]
                    else:
                        message += "Phone number is not valid (+33 form is requiered)\n"
                elif form.cleaned_data["phone"].strip() == "":
                    request.user.phone = ""
                if "affiliation" in form.changed_data:
                    request.user.affiliation = form.cleaned_data["affiliation"]
                elif form.cleaned_data["affiliation"].strip() == "":
                    request.user.affiliation = ""
                if form.cleaned_data["new_password"] != "":
                    if form.cleaned_data["new_password"] == form.cleaned_data["confirmation_new_password"]:
                        if len(form.cleaned_data["new_password"]) >= 8 and any(
                            [not i.isdigit() for i in form.cleaned_data["new_password"]]
                        ):
                            request.user.set_password(form.cleaned_data["new_password"])
                        else:
                            message += "Invalid password\n"
                    else:
                        message += " The confirmation password must be the same \n"
                request.user.save()
                context["message"] = message
            else:
                context["message"] = "Issue submitting the modifications to the website."
        role = "Annotator"
        if request.user.role == "v":
            role = "Viewer"
        elif request.user.role == "r":
            role = "Reviewer"
        form = ChangeForm(
            initial={
                "username": request.user.username,
                "email": request.user.email,
                "role": role,
                "phone": request.user.phone,
                "affiliation": request.user.affiliation,
            }
        )
        if request.method == "POST" and "sub2" in request.POST:
            form2 = RoleChangeRequestForm(request.POST)
            if form2.is_valid():
                role_change_request = form2.save(commit=False)
                role_change_request.user = request.user
                form2.save()
                return redirect(reverse("GenomeTag:main"))
        else:
            form2 = RoleChangeRequestForm()

        context["form"] = form
        context["form2"] = form2
        return render(request, "GenomeTag/loginfo.html", context)


def role_change_request(request):
    if request.method == "POST" and "sub2" in request.POST:
        form2 = RoleChangeRequestForm(request.POST)
        if form2.is_valid():
            role_change_request = form2.save(commit=False)
            role_change_request.user = request.user
            form2.save()
            return redirect(reverse("GenomeTag:main"))
    else:
        form2 = RoleChangeRequestForm()
    return render(request, "GenomeTag/role_change.html", {"form2": form2})


def main(request):
    context = {}
    if not request.user.is_authenticated:
        return render(request, "GenomeTag/main.html", context)
    if request.user.has_perm("GenomeTag.annotate"):
        annot = Annotation.objects.filter(author=request.user).filter(~Q(status="v"))
        attrib = Attribution.objects.filter(annotator=request.user)
        if annot.exists():
            context["annotation"] = annot
        if attrib.exists():
            context["attribution"] = attrib
    if request.user.has_perm("GenomeTag.review"):
        to_review = Annotation.objects.filter(reviewer=request.user, status="u")
        if to_review.exists():
            context["to_review"] = to_review
    user_mailbox_count = Mailbox.objects.filter(user=request.user, read=False).count()
    if user_mailbox_count:
        context["mailbox_count"] = user_mailbox_count
    return render(request, "GenomeTag/main.html", context)


# MISSING PERMS


def attributions(request):
    if not request.user.has_perm("GenomeTag.annotate"):
        return redirect(reverse("GenomeTag:userPermission"))
    allAtrributions = Attribution.objects.filter(annotator=request.user)
    context = {"attributions": allAtrributions}

    user_mailbox_count = Mailbox.objects.filter(user=request.user, read=False).count()
    if user_mailbox_count:
        context["mailbox_count"] = user_mailbox_count
    return render(request, "GenomeTag/attributions.html", context)


def annotations(request):
    if not request.user.has_perm("GenomeTag.annotate"):
        return redirect(reverse("GenomeTag:userPermission"))

    allAnnotations = Annotation.objects.filter(author=request.user)
    context = {"annotations": allAnnotations}

    user_mailbox_count = Mailbox.objects.filter(user=request.user, read=False).count()
    if user_mailbox_count:
        context["mailbox_count"] = user_mailbox_count
    return render(request, "GenomeTag/annotations.html", context)


def reviews_list(request):
    if request.user.has_perm("GenomeTag.review"):
        to_review = Annotation.objects.filter(reviewer=request.user)
        context = {"reviews": to_review}

    user_mailbox_count = Mailbox.objects.filter(user=request.user, read=False).count()
    if user_mailbox_count:
        context["mailbox_count"] = user_mailbox_count
    return render(request, "GenomeTag/reviews_list.html", context)


def create(request):
    if not request.user.has_perm("GenomeTag.annotate"):
        return redirect(reverse("GenomeTag:userPermission"))

    user = request.user

    userAttribution = Attribution.objects.filter(annotator=user)
    attributionIsAnnotatedList = []
    annotationsList = []
    for attribution in userAttribution:
        for possition in attribution.possition.all():
            if Annotation.objects.filter(author=attribution.annotator, position=possition).exists():
                attributionIsAnnotatedList.append(1)
                annotationsList.append(Annotation.objects.filter(author=attribution.annotator, position=possition))
            else:
                attributionIsAnnotatedList.append(0)
                annotationsList.append(None)

    context = {
        "attribution_zip": zip(userAttribution, attributionIsAnnotatedList, annotationsList),
    }
    user_mailbox_count = Mailbox.objects.filter(user=request.user, read=False).count()
    if user_mailbox_count:
        context["mailbox_count"] = user_mailbox_count
    return render(request, "GenomeTag/create.html", context)


def modify_annotation(request, annotation_id):
    if not request.user.has_perm("GenomeTag.annotate"):
        return redirect(reverse("GenomeTag:userPermission"))
    annotation = get_object_or_404(Annotation, accession=annotation_id)
    message = ""
    if request.method == "POST":
        form = AnnotationForm(request.POST)
        if form.is_valid() and request.user == annotation.author:
            annotation.status = "u"
            annotation.commentary = form.cleaned_data["commentary"]
            annotation.accession = form.cleaned_data["accesion"]
            annotation.tags.clear()
            annotation.peptide_set.clear()
            annotation.save()

            tag_ids = request.POST.getlist("tags")  # Assuming you have a 'tags' field in your form
            for tag_id in tag_ids:
                try:
                    tag = Tag.objects.get(pk=tag_id)
                except Exception:
                    message += "Could not add " + tag_id + "\n"
                    continue
                annotation.tags.add(tag)  # Associate the tag with the annotation

            pep_ids = request.POST.getlist("peptide")  # Assuming you have a 'tags' field in your form
            for pep in pep_ids:
                try:

GenomeTag/templates/base.html
<!-- main.html -->
<!DOCTYPE html>
<html lang="en">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block title %}{% endblock %}
  <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'GenomeTag:main' %}">
        <h1 style="margin:0;">GenomeTag</h1>
      </a>
      {% if user.is_authenticated and perms.GenomeTag.view and not user.is_staff and not perms.GenomeTag.review and not perms.GenomeTag.annotate%}
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
      aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'GenomeTag:base' %}">Home
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'GenomeTag:alternative_database' %}">DataBase</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'GenomeTag:search' %}">Search</a>
        </li>
      </ul>

      {% endif %}
      {% if user.is_authenticated and perms.GenomeTag.annotate and not user.is_staff and not perms.GenomeTag.review %}

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
      aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'GenomeTag:base' %}">Home
              <span class="visually-hidden">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'GenomeTag:annotations' %}">Annotations</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'GenomeTag:attributions' %}">Attribution</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'GenomeTag:alternative_database' %}">DataBase</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'GenomeTag:search' %}">Search</a>
          </li>
        </ul>
          {% endif %}
          {% if user.is_authenticated and perms.GenomeTag.review%}
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
          aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'GenomeTag:base' %}">Home
                <span class="visually-hidden">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'GenomeTag:annotations' %}">Annotations</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'GenomeTag:attributions' %}">Attribution</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'GenomeTag:reviews_list' %}">Reviews</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Create</a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'GenomeTag:create_peptide' %}">Peptide</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'GenomeTag:create_attribution' %}">Attribution</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'GenomeTag:alternative_database' %}">DataBase</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'GenomeTag:search' %}">Search</a>
            </li>
            {% if user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'GenomeTag:addfile' %}">Add File</a>
            </li>
            {% endif %}
          </ul>
            {% endif %}
        {% if user.is_authenticated %}
        Hi {{ user.username }} ! &nbsp;&nbsp;
        <form method="post" action="{% url 'logout' %}">
          {% csrf_token %}
          <a href="{% url 'logout' %}" onclick="event.preventDefault(); this.closest('form').submit();">Logout</a>
          <a href="{% url 'GenomeTag:log_info' %}">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
          </svg></a>
          <a href="{% url 'GenomeTag:mailbox' %}" class ="notification">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
              <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414zM0 4.697v7.104l5.803-3.558zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586zm3.436-.586L16 11.801V4.697z"/>
            </svg>          
            {% if mailbox_count > 0 %}
            <span class="badge bg-danger">{{ mailbox_count }}</span>
          {% endif %}</a>
          {%if user.is_authenticated and perms.GenomeTag.annotate or user.is_staff %}
          <a href="{% url 'GenomeTag:forum_main' %}" ><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
            <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5.784 6A2.24 2.24 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.3 6.3 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5"/>
          </svg>
          {% endif %}</a>

        </form>

        {% else %}
        <div class="btn-group" role="group" aria-label="Basic example">
          <a href="{% url 'login' %}" id="login-link">Login</a>
          <span> / </span>
          <a href="{% url 'GenomeTag:signup' %}" id="signup-link">Sign up</a></div>
        {% endif %}


      </div>
  </nav>
</head>

</style>

<body class="body-page">
  {% block content %}
  {% endblock %}

</body>

<!--<footer>
  
  <p>&copy; 2024 GenomeTag. All rights reserved. Made by the BEST TEAM ! </p>

</footer>-->

</html>
{% load static %}

<link rel="stylesheet" href="{% static 'GenomeTag/style.css' %}">

GenomeTag/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
Hi {{ user.username }}!
<form method="post" action="{% url 'logout' %}">
  {% csrf_token %}
  <a href="{% url 'logout' %}" onclick="event.preventDefault(); this.closest('form').submit();">Logout</a>
  <a href="{%url 'userPermission' %}">Permission Exemple</a>
</form>

</form>
{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">Log In /</a>
<a href="{% url 'GenomeTag:signup' %}">Sign Up</a>
{% endif %}
{% endblock %}