GenomeTag/urls.py
from django.urls import path
from . import views
from .views import SignUpView
from . import views

app_name = "GenomeTag"

urlpatterns = [
    path("", views.main, name="main"),
    path("", views.main, name="base"),
    path("userPermission/", views.userPermission, name="userPermission"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("informations/", views.log_info, name="log_info"),
    path("addfile/", views.addfile, name="addfile"),
    path("annotations/", views.annotations, name="annotations"),
    path("attributions/", views.attributions, name="attributions"),
    path("reviews_list/", views.reviews_list, name="reviews_list"),
    path("forum/", views.forum_main, name="forum_main"),
    path("forum/<int:topic_id>/", views.topic, name="topic"),
    path("like/<int:message_id>/", views.like_message, name="like_message"),
    path("create/", views.create, name="create"),
    path("search/", views.search, name="search"),
    path("review/<str:id>/", views.review_add, name="display_review"),
    path("result/", views.result, name="result"),
    path("create/create_peptide", views.create_peptide, name="create_peptide"),
    path(
        "create/create_annotation/<int:attribution_id>/",
        views.create_annotation,
        name="create_annotation",
    ),
    path(
        "create/modify_annotation/<str:annotation_id>/",
        views.modify_annotation,
        name="modify_annotation",
    ),
    path("delete_annotation/<int:attribution_id>/", views.delete_annotation, name="delete_annotation"),
    path("result/Genome/<str:id>/", views.genome, name="display_genome"),
    path("result/Genome/<str:genome_id>/<str:id>/", views.chromosome, name="display_chromosome"),
    path("result/Peptide/<str:id>/", views.peptide, name="display_peptide"),
    path("result/Annotation/<str:id>/", views.annotation, name="display_annotation"),
    path("result/Tag/<str:id>/", views.tag, name="display_tag"),
    path("download_fasta/<str:genome_id>/", views.download_fasta, name="download_fasta"),
    path(
        "download_fasta/<str:genome_id>/<str:chromosome_id>/",
        views.download_fasta_single_chromosome,
        name="download_fasta_single_chromosome",
    ),
    path(
        "download_peptide_fasta/<int:peptide_id>/",
        views.download_peptide_fasta,
        name="download_peptide_fasta",
    ),
    path(
        "download_annotation_fasta/<str:annotation_id>/",
        views.download_annotation_fasta,
        name="download_annotation_fasta",
    ),
    path(
        "download_all_annotation_fasta/<str:genome_id>/<str:chromosome_id>/",
        views.download_all_annotation_fasta,
        name="download_all_annotation_fasta",
    ),
    path("create/create_attribution/", views.create_attribution, name="create_attribution"),
    path("blast/", views.blast, name="blast"),
    path("blast_result/", views.blast_result, name="blast_result"),
    path("alternative_database/", views.alternative_database, name="alternative_database"),
    path("role_change/", views.role_change_request, name="role_change"),
    path("mailbox/", views.mailbox, name="mailbox"),
    path("compose/", views.compose_email, name="compose_email"),
    path("mailbox/<int:message_id>/", views.message_detail, name="message_detail"),
    path("mailbox/<int:message_id>/delete/", views.delete_message, name="delete_message"),
]

projet_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from django.urls import include
from django.views.generic import RedirectView


urlpatterns = [
    path("", RedirectView.as_view(url="/GenomeTag", permanent=False)),
    path("admin/", admin.site.urls),
    path("GenomeTag/", include("GenomeTag.urls")),
    path("GenomeTag/", include("django.contrib.auth.urls")),
]

GenomeTag/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy, reverse
from GenomeTag.models import (
    Genome,
    Chromosome,
    Position,
    Annotation,
    Peptide,
    Attribution,
    CustomUser,
    Tag,
    Review,
    CustomUser,
    Mailbox,
    Topic,
    Message,
)
from django.views.generic.edit import CreateView
from .forms import (
    CustomUserCreationForm,
    AnnotationForm,
    SearchForm,
    ReviewForm,
    PeptideForm,
    ChromosomeDescrForm,
    AttributionForm,
    FileAttributionForm,
    AnnotationDescrForm,
    createPeptideForm,
    ChangeForm,
    RoleChangeRequestForm,
    ComposeForm,
    PositionSelectionForm,
    BacteriaForm,
    TopicForm,
    MessageForm,
    addfileForm,
)
from GenomeTag.search_field import search_dic
import GenomeTag.build_query as bq
from .build_attribution import create_manual_attr, create_file_attr
from django.db.models import Q
import json
from django.views.generic.edit import CreateView
from GenomeTag.search_field import search_dic
import GenomeTag.build_query as bq
import xml.etree.ElementTree as ET
from .blast_utils import perform_blast
from prody import *

# Create your views here.


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"


def log_info(request):
    if request.user.is_authenticated:
        message = ""
        context = {}
        if request.method == "POST" and "sub1" in request.POST:
            form = ChangeForm(request.POST)
            if form.is_valid():
                if "username" in form.changed_data:
                    if (form.cleaned_data["username"] != "" or len(form.cleaned_data["username"]) <= 150) and all(
                        [(i in ["@", "_", "+", "."] or i.isalnum()) for i in form.cleaned_data["username"]]
                    ):
                        request.user.username = form.cleaned_data["username"]
                    else:
                        message += "Invalide username:\n Required. 150 characters or fewer. Usernames may contain alphanumeric, _, @, +, . and - characters. \n"
                if "phone" in form.changed_data:
                    if form.cleaned_data["phone"].is_valid():
                        request.user.phone = form.cleaned_data["phone"]
                    else:
                        message += "Phone number is not valid (+33 form is requiered)\n"
                elif form.cleaned_data["phone"].strip() == "":
                    request.user.phone = ""
                if "affiliation" in form.changed_data:
                    request.user.affiliation = form.cleaned_data["affiliation"]
                elif form.cleaned_data["affiliation"].strip() == "":
                    request.user.affiliation = ""
                if form.cleaned_data["new_password"] != "":
                    if form.cleaned_data["new_password"] == form.cleaned_data["confirmation_new_password"]:
                        if len(form.cleaned_data["new_password"]) >= 8 and any(
                            [not i.isdigit() for i in form.cleaned_data["new_password"]]
                        ):
                            request.user.set_password(form.cleaned_data["new_password"])
                        else:
                            message += "Invalid password\n"
                    else:
                        message += " The confirmation password must be the same \n"
                request.user.save()
                context["message"] = message
            else:
                context["message"] = "Issue submitting the modifications to the website."
        role = "Annotator"
        if request.user.role == "v":
            role = "Viewer"
        elif request.user.role == "r":
            role = "Reviewer"
        form = ChangeForm(
            initial={
                "username": request.user.username,
                "email": request.user.email,
                "role": role,
                "phone": request.user.phone,
                "affiliation": request.user.affiliation,
            }
        )
        if request.method == "POST" and "sub2" in request.POST:
            form2 = RoleChangeRequestForm(request.POST)
            if form2.is_valid():
                role_change_request = form2.save(commit=False)
                role_change_request.user = request.user
                form2.save()
                return redirect(reverse("GenomeTag:main"))
        else:
            form2 = RoleChangeRequestForm()

        context["form"] = form
        context["form2"] = form2
        return render(request, "GenomeTag/loginfo.html", context)


def role_change_request(request):
    if request.method == "POST" and "sub2" in request.POST:
        form2 = RoleChangeRequestForm(request.POST)
        if form2.is_valid():
            role_change_request = form2.save(commit=False)
            role_change_request.user = request.user
            form2.save()
            return redirect(reverse("GenomeTag:main"))
    else:
        form2 = RoleChangeRequestForm()
    return render(request, "GenomeTag/role_change.html", {"form2": form2})


def main(request):
    context = {}
    if not request.user.is_authenticated:
        return render(request, "GenomeTag/main.html", context)
    if request.user.has_perm("GenomeTag.annotate"):
        annot = Annotation.objects.filter(author=request.user).filter(~Q(status="v"))
        attrib = Attribution.objects.filter(annotator=request.user)
        if annot.exists():
            context["annotation"] = annot
        if attrib.exists():
            context["attribution"] = attrib
    if request.user.has_perm("GenomeTag.review"):
        to_review = Annotation.objects.filter(reviewer=request.user, status="u")
        if to_review.exists():
            context["to_review"] = to_review
    user_mailbox_count = Mailbox.objects.filter(user=request.user, read=False).count()
    if user_mailbox_count:
        context["mailbox_count"] = user_mailbox_count
    return render(request, "GenomeTag/main.html", context)


# MISSING PERMS


def attributions(request):
    if not request.user.has_perm("GenomeTag.annotate"):
        return redirect(reverse("GenomeTag:userPermission"))
    allAtrributions = Attribution.objects.filter(annotator=request.user)
    context = {"attributions": allAtrributions}

    user_mailbox_count = Mailbox.objects.filter(user=request.user, read=False).count()
    if user_mailbox_count:
        context["mailbox_count"] = user_mailbox_count
    return render(request, "GenomeTag/attributions.html", context)


def annotations(request):
    if not request.user.has_perm("GenomeTag.annotate"):
        return redirect(reverse("GenomeTag:userPermission"))

    allAnnotations = Annotation.objects.filter(author=request.user)
    context = {"annotations": allAnnotations}

    user_mailbox_count = Mailbox.objects.filter(user=request.user, read=False).count()
    if user_mailbox_count:
        context["mailbox_count"] = user_mailbox_count
    return render(request, "GenomeTag/annotations.html", context)


def reviews_list(request):
    if request.user.has_perm("GenomeTag.review"):
        to_review = Annotation.objects.filter(reviewer=request.user)
        context = {"reviews": to_review}

    user_mailbox_count = Mailbox.objects.filter(user=request.user, read=False).count()
    if user_mailbox_count:
        context["mailbox_count"] = user_mailbox_count
    return render(request, "GenomeTag/reviews_list.html", context)


def create(request):
    if not request.user.has_perm("GenomeTag.annotate"):
        return redirect(reverse("GenomeTag:userPermission"))

    user = request.user

    userAttribution = Attribution.objects.filter(annotator=user)
    attributionIsAnnotatedList = []
    annotationsList = []
    for attribution in userAttribution:
        for possition in attribution.possition.all():
            if Annotation.objects.filter(author=attribution.annotator, position=possition).exists():
                attributionIsAnnotatedList.append(1)
                annotationsList.append(Annotation.objects.filter(author=attribution.annotator, position=possition))
            else:
                attributionIsAnnotatedList.append(0)
                annotationsList.append(None)

    context = {
        "attribution_zip": zip(userAttribution, attributionIsAnnotatedList, annotationsList),
    }
    user_mailbox_count = Mailbox.objects.filter(user=request.user, read=False).count()
    if user_mailbox_count:
        context["mailbox_count"] = user_mailbox_count
    return render(request, "GenomeTag/create.html", context)


def modify_annotation(request, annotation_id):
    if not request.user.has_perm("GenomeTag.annotate"):
        return redirect(reverse("GenomeTag:userPermission"))
    annotation = get_object_or_404(Annotation, accession=annotation_id)
    message = ""
    if request.method == "POST":
        form = AnnotationForm(request.POST)
        if form.is_valid() and request.user == annotation.author:
            annotation.status = "u"
            annotation.commentary = form.cleaned_data["commentary"]
            annotation.accession = form.cleaned_data["accesion"]
            annotation.tags.clear()
            annotation.peptide_set.clear()
            annotation.save()

            tag_ids = request.POST.getlist("tags")  # Assuming you have a 'tags' field in your form
            for tag_id in tag_ids:
                try:
                    tag = Tag.objects.get(pk=tag_id)
                except Exception:
                    message += "Could not add " + tag_id + "\n"
                    continue
                annotation.tags.add(tag)  # Associate the tag with the annotation

            pep_ids = request.POST.getlist("peptide")  # Assuming you have a 'tags' field in your form
            for pep in pep_ids:
                try:

GenomeTag/templates/GenomeTag/addfile.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block content %}
<!DOCTYPE html>
<html>

<head>
  <title>Add File</title>
</head>

<body id="body" class="body-page">
  <div id="error1" class="center-container-err">
    <div class="alert alert-dismissible alert-success">
      <h1>Add file:</h1>
      <strong> be sure that the file is correclty formated</strong>
      <br>

      <form enctype="multipart/form-data" action="./" method="post">

        {% csrf_token %}

        Genome File (requiered): {{form.genome_file}}<br>
        CDS File: {{form.cds_file}}<br>
        Peptide File: {{form.peptide_file}}<br>

        <br>
        <button type="submit" class="btn btn-primary">ADD</button>

      </form>
      <br>
      <a href="/GenomeTag/">Home Page</a>
    </div>
</body>

</html>
{% endblock %}

GenomeTag/templates/GenomeTag/create_annotation.html
<!-- create_annotation.html -->

{% extends 'base.html' %}

<html lang="en">

{% load static %}

<link rel="stylesheet" href="{% static 'GenomeTag/style.css' %}">

{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Annotation Form</title>
</head>

<body class="body-page">


  {% if message %}
  {{message}}
  {% endif %}

  <div id=container class=" center-container2">
    <h4>Here is what will be saved as your annotation:</h4>
    <label for="author">Author:</label>
    <input type="text" id="author" name="author" value="{{ attribution.annotator.email }}" readonly><br>

    <label for="author">Requester:</label>
    <input type="text" id="requester" name="reqester" value="{{ attribution.requester.email }}" readonly><br>

    <label for="author">Status:</label>
    <input type="text" id="status" name="status" value="unreviewed" readonly><br>
    <label for="pos">Positions:</label><br>
    ---------
    {% for pos in attribution.possition.all %}
    <fieldset>
      <label for="position_start">Genome : </label> <input type="text" id="genome" name="genome"
        value="{{ pos.chromosome.genome.id}}" readonly><br>
      <label for="position_start">Chromosome : </label> <input type="text" id="chromoeomse" name="chromosome"
        value="{{ pos.chromosome.accession_number}} " readonly><br>
      <label for="position_start">Strand : </label> <input type="text" id="position_strand" name="position_strand"
        value="{{pos.strand}}" readonly><br>
      <label for="position_start">Start : </label> <input type="text" id="position_start" name="position_start"
        value="{{ pos.start }}" readonly><br>
      <label for="position_end">End : </label> <input type="text" id="position_end" name="position_end"
        value="{{ pos.end }}" readonly><br>
      <br>
      ---------
    </fieldset>
    {% endfor %}
    <form method="post" id="annot_form">
      {% csrf_token %}
      {{ form.as_p }} <!-- Render form fields as paragraphs -->
      <br>
      <h5>Add linked Peptides (by accession number)</h5>
      <br id="spacing">
      <br>
      <button class="btn btn-outline-primary" type="submit" value="+" id="add" name="add" formnovalidate> + </button>
      <br>
      <br>
      <button class="btn btn-outline-primary" type="submit" id="launch" name="launch" form="annot_form" formaction="./"
        method="POST">CREATE</button>
    </form>
    <script>
      function add_condition() {

        var new_field = document.createElement('fieldset');
        //SUPPRESS ASAP
        var pep = document.createElement('input');
        pep.type = "text";
        pep.name = "peptide";

        var supp = document.createElement('button');
        supp.setAttribute("formnovalidate", true)
        supp.value = " ";
        supp.name = "delete";
        supp.className = 'btn-close';
        // Attach the event handler to the "x" button
        supp.addEventListener('click', (sub) => {
          console.log("ici");
          sub.stopPropagation();
          sub.preventDefault();
          suppress_condition(supp);
          return false;
        });
        // Append the result element to the container


        // Append the result element to the container

        new_field.appendChild(pep);
        //new_field.innerHTML += '  ';
        new_field.appendChild(supp);
        //new_field.innerHTML += '  ';



        var add_button = document.getElementById('spacing');
        var resultContainer = document.getElementById('annot_form');

        resultContainer.insertBefore(new_field, add_button);
      }

      function suppress_condition(e) {
        // Remove the element referenced by e.parentNode
        e.parentNode.parentNode.removeChild(e.parentNode);
      }

      document.addEventListener('DOMContentLoaded', function () {
        document.getElementById("add").addEventListener('click', function (event) {
          // Call the function defined in the external file
          add_condition();
          event.preventDefault();
        });
      });
    </script>
  </div>
  {% endblock %}
</body>

</html>

GenomeTag/templates/GenomeTag/create_attribution.html
<!DOCTYPE html>
<html lang="en">
{% extends "base.html" %}

{% block content %}
{% load static %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Creation of Attribution</title>
</head>

<body>
  <script src="{% static '/GenomeTag/attribution_form.js' %}"></script>
  <br>

  {% if message %}
  {% if message == 'Attribution created succesfuly' or message == 'The whole file has been processed correctly' %}
  <div class="center-container-err">
    <div class="alert alert-dismissible alert-success">
      <h4 class="alert-heading">Congrats!</h4>
      <p class="mb-0"> {{message}} <a href="{% url 'GenomeTag:create_attribution' %}" class="alert-link">Attribute
          another</a>.</p>
    </div>
  </div>
  {%else%}
  <div class="center-container-err">
    <div class="alert alert-dismissible alert-warning">
      <h4 class="alert-heading">Warning!</h4>
      <p class="mb-0"> {{message}} <a href="{% url 'GenomeTag:create_attribution' %}" class="alert-link">Try
          again</a>.</p>
    </div>
  </div>
  {%endif%}
  {% else %}
  <div class="center-container2">
    <div class="text-center">
      <h1>Attribute a position to annotator</h1>
    </div>
    <br>
    <h1>Create attribution manually</h1>
    <form method="post" action="{% url 'GenomeTag:create_attribution' %}" id="position_form">
      {% csrf_token %}
      Creator {{form.Creator}} Annotator {{form.Annotator}}
      <br>
      <h3>Position(s) among Annotable Genome:</h3>
      <div>Chromosome Strand Start End</div>
      <fieldset>{{form.Chromosome}} {{form.Strand}} {{form.Start}} {{form.End}}</fieldset>
      <br id="end">
      <button type="button" class="btn btn-outline-primary" id="add">+</button>
      <br>
      <br>
      <button type="submit" class="btn btn-primary" name="sub1" value="Submit Manually">Submit</button>
    </form>
    <h1>Create upload attribution file</h1>
    <div>file line example: <br>
      [Annotator-mail]\t[genome]\t[chromosome]\t[strand]\t[start]\t[end]\t[chromosome]\t[start]\t[end][\t...]<br>...
    </div>
    <br>
    <a href="{% static '/example.tsv' %}" download>example_file</a>
    <br>
    <br>
    <form method="post" enctype="multipart/form-data" action="{% url 'GenomeTag:create_attribution' %}"
      id="position_form">
      Creator {{form2.Creator}} <br> <br>
      {% csrf_token %}
      {{form2.File}}
      <br>
      <br>
      <button type="submit" class="btn btn-primary" name="sub2" value="Submit File">Submit File</button>
    </form>
  </div>
  {% endif %}
</body>
{%endblock%}

</html>

GenomeTag/templates/GenomeTag/create_peptide.html
{% extends 'base.html' %}

<html lang="en">

{% load static %}

<link rel="stylesheet" href="{% static 'GenomeTag/style.css' %}">
<!DOCTYPE html>

{% block content %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>

<body class=" body-page">
  <div id=container class=" center-container2">
    <h4>Here you can create new peptide that will be stored in the database. The purpose of these peptides is to be
      linked to one or multiples annotations.</h4>
    <form method="post" id="peptide_form">
      {% csrf_token %}
      {{ form.as_p }} <!-- Render form fields as paragraphs -->
      <button class="btn btn-outline-primary" type="submit">Submit</button> <!-- Add a submit button -->
    </form>

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </div>

</body>

</html>

GenomeTag/templates/GenomeTag/delete_confirm.html
{% extends "base.html" %}
{% load static %}

<link rel="stylesheet" href="{% static 'GenomeTag/style.css' %}">
<!DOCTYPE html>
{% block content %}
<div class="center-container">
  <h1>Confirm Deletion</h1>
  <p>Are you sure you want to delete the message "{{ message.subject }}"?</p>
  <form method="post">
    {% csrf_token %}

    <button type="submit" class="btn btn-primary btn-lg text-center">Confirm</button>
    <a href="../"><button type="submit" class="btn btn-primary btn-lg text-center">Cancel</button></a>

  </form>
</div>
{% endblock %}

GenomeTag/templates/GenomeTag/error_result.html
<!-- err_result.html -->

{% extends 'base.html' %}

<html lang="en">

{% load static %}

<link rel="stylesheet" href="{% static 'GenomeTag/style.css' %}">
<!DOCTYPE html>
{% block content %}


<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Search Error</title>

</head>
{{ data|json_script:'mydata'}}

<body id="body" class="body-page">

  <div id="error1" class="center-container-err">
    <div id="error2" class="alert alert-dismissible alert-danger">
      <div class="text-black"> The query could not be processed due to an error</div>
      <h2> Error encountered :</h2>

      <script>
        const data = JSON.parse(document.getElementById('mydata').textContent);
        console.log(data['code1']);
        console.log(data['code2']);
        err = document.createElement("p");
        error_message = "";
        switch (data['code1']) {
          case -1: if (data['code2'] == 0 || data['code2'] == 2) {
            error_message = "Fatal Error on the query form sent to the site";
          }
          else if (data['code2'] == 3) {
            error_message = "No condition with value filled in the query";
          }
          else {
            error_message = data['code2'] + " is not a possible entity searched";
          }
            break;
          case 1: error_message = "Condition selected unkown for this type of result in condition " + data['code2']; break;
          case 2: error_message = "Unrecognized option selected before condition number " + data['code2'] + " must be either \'HAS\' or \'HAS NOT\'"; break;
          case 3: error_message = "Unrecognized option selected as logical connector before condition number " + data['code2']; break;
          case 4: error_message = "Incompatile value filled on the condition number " + data['code2']; break;
          default:
            error_message = "Impossible to figure out what is wronge more precisely";
        }
        console.log(error_message);
        err.textContent = error_message;
        error = document.getElementById("body").append(err);
        document.getElementById("error2").append(err);

      </script>

      <strong>Oh snap!</strong> <a href="/GenomeTag/search/" class="alert-link">Change a few things up</a> and try
      submitting again.
      Go back to the <a href="/GenomeTag/">Home Page</a>

    </div>
  </div>
  {% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>

</html>

GenomeTag/templates/GenomeTag/mailbox.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block content %}

<div class="center-container2">
  <h1>Mailbox</h1>
  <ul>
    {% if user_mailbox %}
    {% for message in user_mailbox %}
    <li>
      <strong>{{ message.sender }}:</strong>
      <a href="{% url 'GenomeTag:message_detail' message.id %}">{{ message.subject }}&nbsp;&nbsp;</a>

      <a href="{% url 'GenomeTag:delete_message' message.id %}"><svg xmlns="http://www.w3.org/2000/svg" width="20"
          height="30" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
          <path
            d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06m6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528M8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5" />
        </svg></a>
    </li>
    {% endfor %}
    {% else %}
    <p>You have no new messages.</p>
    {% endif %}
    <br>
    <br>
    <br>

    <a class="btn btn-primary btn-lg text-center" href="{% url 'GenomeTag:compose_email' %}" role="button">Send a
      message</a>
  </ul>
</div>
{% endblock %}

GenomeTag/templates/GenomeTag/message_detail.html
{% extends "base.html" %}

<html lang="en">

{% load static %}

<link rel="stylesheet" href="{% static 'GenomeTag/style.css' %}">
<!DOCTYPE html>

{% block content %}
<div class="center-container">
  <h1>{{ message.subject }}</h1>
  <p><strong>From:</strong> {{ message.sender }}</p>
  <p><strong>Message:</strong> {{ message.message }}</p>
  <a href="{% url 'GenomeTag:delete_message' message.id %}"><svg xmlns="http://www.w3.org/2000/svg" width="30"
      height="30" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
      <path
        d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06m6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528M8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5" />
    </svg></a>
</div>
{% endblock %}

GenomeTag/templates/GenomeTag/role_change.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block content %}
<div class="center-container2">
  <h2>Role Change Request</h2>
  <form method="post" action="./">
    {% csrf_token %}
    {{ form2.as_p }}

    <button type="submit" class="btn btn-primary" name="sub2">Submit Role Change Request</button>
  </form>
</div>
{% endblock %}