GenomeTag/urls.py
from django.urls import path
from . import views
from .views import SignUpView
from . import views

app_name = "GenomeTag"

urlpatterns = [
    path("", views.main, name="main"),
    path("", views.main, name="base"),
    path("userPermission/", views.userPermission, name="userPermission"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("informations/", views.log_info, name="log_info"),
    path("addfile/", views.addfile, name="addfile"),
    path("annotations/", views.annotations, name="annotations"),
    path("attributions/", views.attributions, name="attributions"),
    path("reviews_list/", views.reviews_list, name="reviews_list"),
    path("forum/", views.forum_main, name="forum_main"),
    path("forum/<int:topic_id>/", views.topic, name="topic"),
    path("like/<int:message_id>/", views.like_message, name="like_message"),
    path("create/", views.create, name="create"),
    path("search/", views.search, name="search"),
    path("review/<str:id>/", views.review_add, name="display_review"),
    path("result/", views.result, name="result"),
    path("create/create_peptide", views.create_peptide, name="create_peptide"),
    path(
        "create/create_annotation/<int:attribution_id>/",
        views.create_annotation,
        name="create_annotation",
    ),
    path(
        "create/modify_annotation/<str:annotation_id>/",
        views.modify_annotation,
        name="modify_annotation",
    ),
    path("delete_annotation/<int:attribution_id>/", views.delete_annotation, name="delete_annotation"),
    path("result/Genome/<str:id>/", views.genome, name="display_genome"),
    path("result/Genome/<str:genome_id>/<str:id>/", views.chromosome, name="display_chromosome"),
    path("result/Peptide/<str:id>/", views.peptide, name="display_peptide"),
    path("result/Annotation/<str:id>/", views.annotation, name="display_annotation"),
    path("result/Tag/<str:id>/", views.tag, name="display_tag"),
    path("download_fasta/<str:genome_id>/", views.download_fasta, name="download_fasta"),
    path(
        "download_fasta/<str:genome_id>/<str:chromosome_id>/",
        views.download_fasta_single_chromosome,
        name="download_fasta_single_chromosome",
    ),
    path(
        "download_peptide_fasta/<int:peptide_id>/",
        views.download_peptide_fasta,
        name="download_peptide_fasta",
    ),
    path(
        "download_annotation_fasta/<str:annotation_id>/",
        views.download_annotation_fasta,
        name="download_annotation_fasta",
    ),
    path(
        "download_all_annotation_fasta/<str:genome_id>/<str:chromosome_id>/",
        views.download_all_annotation_fasta,
        name="download_all_annotation_fasta",
    ),
    path("create/create_attribution/", views.create_attribution, name="create_attribution"),
    path("blast/", views.blast, name="blast"),
    path("blast_result/", views.blast_result, name="blast_result"),
    path("alternative_database/", views.alternative_database, name="alternative_database"),
    path("role_change/", views.role_change_request, name="role_change"),
    path("mailbox/", views.mailbox, name="mailbox"),
    path("compose/", views.compose_email, name="compose_email"),
    path("mailbox/<int:message_id>/", views.message_detail, name="message_detail"),
    path("mailbox/<int:message_id>/delete/", views.delete_message, name="delete_message"),
]

projet_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from django.urls import include
from django.views.generic import RedirectView


urlpatterns = [
    path("", RedirectView.as_view(url="/GenomeTag", permanent=False)),
    path("admin/", admin.site.urls),
    path("GenomeTag/", include("GenomeTag.urls")),
    path("GenomeTag/", include("django.contrib.auth.urls")),
]

GenomeTag/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy, reverse
from GenomeTag.models import (
    Genome,
    Chromosome,
    Position,
    Annotation,
    Peptide,
    Attribution,
    CustomUser,
    Tag,
    Review,
    CustomUser,
    Mailbox,
    Topic,
    Message,
)
from django.views.generic.edit import CreateView
from .forms import (
    CustomUserCreationForm,
    AnnotationForm,
    SearchForm,
    ReviewForm,
    PeptideForm,
    ChromosomeDescrForm,
    AttributionForm,
    FileAttributionForm,
    AnnotationDescrForm,
    createPeptideForm,
    ChangeForm,
    RoleChangeRequestForm,
    ComposeForm,
    PositionSelectionForm,
    BacteriaForm,
    TopicForm,
    MessageForm,
    addfileForm,
)
from GenomeTag.search_field import search_dic
import GenomeTag.build_query as bq
from .build_attribution import create_manual_attr, create_file_attr
from django.db.models import Q
import json
from django.views.generic.edit import CreateView
from GenomeTag.search_field import search_dic
import GenomeTag.build_query as bq
import xml.etree.ElementTree as ET
from .blast_utils import perform_blast
from prody import *

# Create your views here.


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"


def log_info(request):
    if request.user.is_authenticated:
        message = ""
        context = {}
        if request.method == "POST" and "sub1" in request.POST:
            form = ChangeForm(request.POST)
            if form.is_valid():
                if "username" in form.changed_data:
                    if (form.cleaned_data["username"] != "" or len(form.cleaned_data["username"]) <= 150) and all(
                        [(i in ["@", "_", "+", "."] or i.isalnum()) for i in form.cleaned_data["username"]]
                    ):
                        request.user.username = form.cleaned_data["username"]
                    else:
                        message += "Invalide username:\n Required. 150 characters or fewer. Usernames may contain alphanumeric, _, @, +, . and - characters. \n"
                if "phone" in form.changed_data:
                    if form.cleaned_data["phone"].is_valid():
                        request.user.phone = form.cleaned_data["phone"]
                    else:
                        message += "Phone number is not valid (+33 form is requiered)\n"
                elif form.cleaned_data["phone"].strip() == "":
                    request.user.phone = ""
                if "affiliation" in form.changed_data:
                    request.user.affiliation = form.cleaned_data["affiliation"]
                elif form.cleaned_data["affiliation"].strip() == "":
                    request.user.affiliation = ""
                if form.cleaned_data["new_password"] != "":
                    if form.cleaned_data["new_password"] == form.cleaned_data["confirmation_new_password"]:
                        if len(form.cleaned_data["new_password"]) >= 8 and any(
                            [not i.isdigit() for i in form.cleaned_data["new_password"]]
                        ):
                            request.user.set_password(form.cleaned_data["new_password"])
                        else:
                            message += "Invalid password\n"
                    else:
                        message += " The confirmation password must be the same \n"
                request.user.save()
                context["message"] = message
            else:
                context["message"] = "Issue submitting the modifications to the website."
        role = "Annotator"
        if request.user.role == "v":
            role = "Viewer"
        elif request.user.role == "r":
            role = "Reviewer"
        form = ChangeForm(
            initial={
                "username": request.user.username,
                "email": request.user.email,
                "role": role,
                "phone": request.user.phone,
                "affiliation": request.user.affiliation,
            }
        )
        if request.method == "POST" and "sub2" in request.POST:
            form2 = RoleChangeRequestForm(request.POST)
            if form2.is_valid():
                role_change_request = form2.save(commit=False)
                role_change_request.user = request.user
                form2.save()
                return redirect(reverse("GenomeTag:main"))
        else:
            form2 = RoleChangeRequestForm()

        context["form"] = form
        context["form2"] = form2
        return render(request, "GenomeTag/loginfo.html", context)


def role_change_request(request):
    if request.method == "POST" and "sub2" in request.POST:
        form2 = RoleChangeRequestForm(request.POST)
        if form2.is_valid():
            role_change_request = form2.save(commit=False)
            role_change_request.user = request.user
            form2.save()
            return redirect(reverse("GenomeTag:main"))
    else:
        form2 = RoleChangeRequestForm()
    return render(request, "GenomeTag/role_change.html", {"form2": form2})


def main(request):
    context = {}
    if not request.user.is_authenticated:
        return render(request, "GenomeTag/main.html", context)
    if request.user.has_perm("GenomeTag.annotate"):
        annot = Annotation.objects.filter(author=request.user).filter(~Q(status="v"))
        attrib = Attribution.objects.filter(annotator=request.user)
        if annot.exists():
            context["annotation"] = annot
        if attrib.exists():
            context["attribution"] = attrib
    if request.user.has_perm("GenomeTag.review"):
        to_review = Annotation.objects.filter(reviewer=request.user, status="u")
        if to_review.exists():
            context["to_review"] = to_review
    user_mailbox_count = Mailbox.objects.filter(user=request.user, read=False).count()
    if user_mailbox_count:
        context["mailbox_count"] = user_mailbox_count
    return render(request, "GenomeTag/main.html", context)


# MISSING PERMS


def attributions(request):
    if not request.user.has_perm("GenomeTag.annotate"):
        return redirect(reverse("GenomeTag:userPermission"))
    allAtrributions = Attribution.objects.filter(annotator=request.user)
    context = {"attributions": allAtrributions}

    user_mailbox_count = Mailbox.objects.filter(user=request.user, read=False).count()
    if user_mailbox_count:
        context["mailbox_count"] = user_mailbox_count
    return render(request, "GenomeTag/attributions.html", context)


def annotations(request):
    if not request.user.has_perm("GenomeTag.annotate"):
        return redirect(reverse("GenomeTag:userPermission"))

    allAnnotations = Annotation.objects.filter(author=request.user)
    context = {"annotations": allAnnotations}

    user_mailbox_count = Mailbox.objects.filter(user=request.user, read=False).count()
    if user_mailbox_count:
        context["mailbox_count"] = user_mailbox_count
    return render(request, "GenomeTag/annotations.html", context)


def reviews_list(request):
    if request.user.has_perm("GenomeTag.review"):
        to_review = Annotation.objects.filter(reviewer=request.user)
        context = {"reviews": to_review}

    user_mailbox_count = Mailbox.objects.filter(user=request.user, read=False).count()
    if user_mailbox_count:
        context["mailbox_count"] = user_mailbox_count
    return render(request, "GenomeTag/reviews_list.html", context)


def create(request):
    if not request.user.has_perm("GenomeTag.annotate"):
        return redirect(reverse("GenomeTag:userPermission"))

    user = request.user

    userAttribution = Attribution.objects.filter(annotator=user)
    attributionIsAnnotatedList = []
    annotationsList = []
    for attribution in userAttribution:
        for possition in attribution.possition.all():
            if Annotation.objects.filter(author=attribution.annotator, position=possition).exists():
                attributionIsAnnotatedList.append(1)
                annotationsList.append(Annotation.objects.filter(author=attribution.annotator, position=possition))
            else:
                attributionIsAnnotatedList.append(0)
                annotationsList.append(None)

    context = {
        "attribution_zip": zip(userAttribution, attributionIsAnnotatedList, annotationsList),
    }
    user_mailbox_count = Mailbox.objects.filter(user=request.user, read=False).count()
    if user_mailbox_count:
        context["mailbox_count"] = user_mailbox_count
    return render(request, "GenomeTag/create.html", context)


def modify_annotation(request, annotation_id):
    if not request.user.has_perm("GenomeTag.annotate"):
        return redirect(reverse("GenomeTag:userPermission"))
    annotation = get_object_or_404(Annotation, accession=annotation_id)
    message = ""
    if request.method == "POST":
        form = AnnotationForm(request.POST)
        if form.is_valid() and request.user == annotation.author:
            annotation.status = "u"
            annotation.commentary = form.cleaned_data["commentary"]
            annotation.accession = form.cleaned_data["accesion"]
            annotation.tags.clear()
            annotation.peptide_set.clear()
            annotation.save()

            tag_ids = request.POST.getlist("tags")  # Assuming you have a 'tags' field in your form
            for tag_id in tag_ids:
                try:
                    tag = Tag.objects.get(pk=tag_id)
                except Exception:
                    message += "Could not add " + tag_id + "\n"
                    continue
                annotation.tags.add(tag)  # Associate the tag with the annotation

            pep_ids = request.POST.getlist("peptide")  # Assuming you have a 'tags' field in your form
            for pep in pep_ids:
                try:

GenomeTag/templates/GenomeTag/display/display_annotation.html
<!-- genome_detail.html -->
{% extends 'base.html' %}

<html lang="en">

{% load static %}

<link rel="stylesheet" href="{% static 'GenomeTag/style.css' %}">

<!DOCTYPE html>
{% block content %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  <title>Annotation Detail</title>
</head>

<body>
  <div class="center-container2">
    <h1>Annotation: {{ annotation.accession}} ( made by: {{annotation.author}})
      {% if annotation.status == 'u' %}
      <button type="button" class="btn btn-warning disabled">Status: Unreviewed</button>
      {% elif annotation.status == 'r' %}
      <button type="button" class="btn btn-danger disabled">Status: Rejected</button>
      {%else%}
      <button type="button" class="btn btn-success disabled">Status: Validated</button>
      {% endif %}
    </h1>
    <form method="post" action="{% url 'GenomeTag:download_annotation_fasta' annotation.accession %}">
      {% csrf_token %}
      <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
        <button type="submit" class="btn btn-primary">FASTA</button>
        <div class="btn-group" role="group">
          <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle show"
            data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="true"></button>
          <div class="dropdown-menu " aria-labelledby="btnGroupDrop1"
            style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate(0px, 40px);"
            data-popper-placement="bottom-start">
            <a class="dropdown-item"><label><input type="checkbox" name="include_genome" checked> Include
                Genome</label></a>
            <a class="dropdown-item"><label><input type="checkbox" name="include_chromosome" checked> Include
                Chromosome</label></a>
            <a class="dropdown-item"><label><input type="checkbox" name="include_sequence" checked> Include
                Sequence</label></a>
            <a class="dropdown-item"><label><input type="checkbox" name="include_start" checked> Include
                Start</label></a>
            <a class="dropdown-item"><label><input type="checkbox" name="include_end" checked> Include End</label></a>
            <a class="dropdown-item"><label><input type="checkbox" name="include_start_relative" checked> Include Start
                Relative</label></a>
            <a class="dropdown-item"><label><input type="checkbox" name="include_end_relative" checked> Include End
                Relative</label></a>
            <a class="dropdown-item"><label><input type="checkbox" name="include_status" checked> Include
                Status</label></a>
          </div>
        </div>
      </div>
    </form>
    <br>
    <p>{{annotation.commentary}}</p>
    <br>
    <h2>Localisation</h2>

    <ul>
      {% for pos in annotation.position.all %}
      <p><a href="../../Genome/{{pos.chromosome.genome.id}}/{{pos.chromosome.accession_number}}"> {{
          pos.chromosome.accession_number}}</a> start: {{ pos.start}} ({{pos.start_relative}}) end: {{ pos.end}}
        ({{pos.end_relative}})</p>
      {% endfor %}
    </ul>
    {% if annotation.tags.all %}
    <h2>List of Tags</h2>
    <ul>
      {% for tag in annotation.tags.all %}
      <p><a href="../../Tag/{{tag.tag_id}}">{{tag.tag_id}}</a></p>
      {% endfor %}
    </ul>
    {% endif %}

    {%if peptide%}
    <h2>Linked Peptide</h2>
    {%endif%}
    <ul>
      {% for pep in peptide %}
      <p><a href="../../Peptide/{{pep.accesion}}">{{pep.accesion}}</a></p>
      {% endfor %}
    </ul>

    <h2>Blast</h2>
    <a href="{% url 'GenomeTag:blast' %}?annotation_id={{ annotation.id }}&type=annotation"><button
        class="btn btn-primary">Blast this peptide</button></a>
  </div>
  {% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>

</html>

GenomeTag/templates/GenomeTag/display/display_genome.html
<!-- genome_detail.html -->


{% extends 'base.html' %}

<html lang="en">

{% load static %}

<link rel="stylesheet" href="{% static 'GenomeTag/style.css' %}">
<!DOCTYPE html>
{% block content %}

<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Genome Detail</title>
</head>

<body class="body-page">
  <div class="center-container2">
    <h1>Genome Detail</h1>
    <h2>{{ genome.id }} ({%if genome.annotable %}Annotable{% else %} Non Annotable {%endif%})</h2>

    <p>{{ genome.commentary}}</p>
    <p>{{ genome.species}}</p>
    {% if genome.DOI%}
    <p>DOI: {{ genome.DOI}}</p>
    {%endif%}

    <h2>Chromosome:</h2>
    <form method="post" action="{% url 'GenomeTag:download_fasta' genome.id %}">
      {% csrf_token %}
      <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
        <button type="submit" class="btn btn-primary">DOWNLOAD ALL</button>
        <div class="btn-group" role="group">
          <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle show"
            data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="true"></button>
          <div class="dropdown-menu " aria-labelledby="btnGroupDrop1"
            style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate(0px, 40px);"
            data-popper-placement="bottom-start">
            <a class="dropdown-item"><label><input type="checkbox" name="include_accession_number" checked> Include
                Accession Number</label></a>
            <a class="dropdown-item"><label><input type="checkbox" name="include_genome" checked> Include
                Genome</label></a>
            <a class="dropdown-item"><label><input type="checkbox" name="include_sequence" checked> Include
                Sequence</label></a>
            <a class="dropdown-item"><label><input type="checkbox" name="include_start" checked> Include
                Start</label></a>
            <a class="dropdown-item"><label><input type="checkbox" name="include_end" checked> Include End</label></a>
          </div>
        </div>
      </div>
    </form>
    <br>
    <ul>

      <table class="table table-active">
        <thead>
          <tr>
            <th scope="col">Accession number</th>
            <th scope="col">End</th>
            <th scope="col">Start</th>
            <th scope="col">Fasta</th>
          </tr>
        </thead>
        <tbody>
          {% for cr in chromosome %}
          <tr class="table table-light">
            <th scope="row"><a href="./{{cr.accession_number}}">{{ cr.accession_number}} </a></th>
            <td>{{cr.start}}</td>
            <td>{{cr.end}}</td>
            <td>
              <form method="post"
                action="{% url 'GenomeTag:download_fasta_single_chromosome' genome.id cr.accession_number %}">
                {% csrf_token %}
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                  <button type="submit" class="btn btn-primary">FASTA</button>
                  <div class="btn-group" role="group">
                    <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle show"
                      data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="true"></button>
                    <div class="dropdown-menu " aria-labelledby="btnGroupDrop1"
                      style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate(0px, 40px);"
                      data-popper-placement="bottom-start">
                      <a class="dropdown-item"><label><input type="checkbox" name="include_accession_number" checked>
                          Include Accession Number</label></a>
                      <a class="dropdown-item"><label><input type="checkbox" name="include_genome" checked> Include
                          Genome</label></a>
                      <a class="dropdown-item"><label><input type="checkbox" name="include_sequence" checked> Include
                          Sequence</label></a>
                      <a class="dropdown-item"><label><input type="checkbox" name="include_start" checked> Include
                          Start</label></a>
                      <a class="dropdown-item"><label><input type="checkbox" name="include_end" checked> Include
                          End</label></a>
                    </div>
                  </div>
                </div>
              </form>
            </td>

          </tr>
        </tbody>
      </table>
      {% endfor %}
  </div>
  </ul>
  {% endblock %}
</body>

</html>

GenomeTag/templates/GenomeTag/display/display_tag.html
{% extends 'base.html' %}

<html lang="en">

{% load static %}

<link rel="stylesheet" href="{% static 'GenomeTag/style.css' %}">

<!DOCTYPE html>
{% block content %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  <title>TAG</title>
</head>

<body>
  <div class="center-container2">
    <h1>Tag: {{ tag.tag_id}}</h1>
    <p>{{tag.text}}</p>

    <h2>All Available Tags:</h2>
    <ul>
      <div class="row">
        {% for t in all_tags %}
        <div class="col-md-4 mb-3 ">
          <div class="card bg-secondary d-flex h-100" style="max-width: 20rem;">
            <div class="card-header">TAGS</div>
            <div class="card-body">
              <h4 class="card-title">{{ t.tag_id }}</h4>
              <p class="card-text ">{{ t.text }}</p>


            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </ul>
  </div>
  {% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>

</html>


<div class="card-header">Header</div>
<div class="card-body">
  <h4 class="card-title">Primary card title</h4>

</div>